ERROR    - 2023-09-17 14:57:09,735. В модуле "__main__" в строке 031 функция "wrapper()" в 1694951829.7352085 секунд записала сообщение: Функция num_check с аргументами args = ('None',), kwargs ={} выдвала ошибку: message_errors = ValueError("invalid literal for int() with base 10: 'None'")
ERROR    - 2023-09-17 14:57:28,958. В модуле "__main__" в строке 031 функция "wrapper()" в 1694951848.9587739 секунд записала сообщение: Функция num_check с аргументами args = ('ntrcn',), kwargs ={} выдвала ошибку: message_errors = ValueError("invalid literal for int() with base 10: 'ntrcn'")
